apiVersion: v1
kind: Service
metadata:
  name: display-homelab # Sets service name
  labels:
    app: display-homelab # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 8080 # Sets port to run the application 
  selector:
    app: display-homelab